// movies calls
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
export const GET_MOVIES_ERROR = 'GET_MOVIES_ERROR';

export const GET_NEW_MOVIES_SUCCESS = 'GET_NEW_MOVIES_SUCCESS';
export const GET_NEW_MOVIES_ERROR = 'GET_NEW_MOVIES_ERROR';

export const GET_POPULAR_MOVIES_SUCCESS = 'GET_POPULAR_MOVIES_SUCCESS';
export const GET_POPULAR_MOVIES_ERROR = 'GET_POPULAR_MOVIES_ERROR';

export const GET_GENRES_SUCCESS = 'GET_GENRES_SUCCESS';
export const GET_GENRES_ERROR = 'GET_GENRES_ERROR';

export const GET_MOVIE_SUCCESS = 'GET_MOVIE_SUCCESS';
export const GET_MOVIE_ERROR = 'GET_MOVIE_ERROR';
export const CLEAR_MOVIE_INFO = 'CLEAR_MOVIE_INFO';

export const GET_VIDEOS_SUCCESS = 'GET_VIDEOS_SUCCESS';
export const GET_VIDEOS_ERROR = 'GET_VIDEOS_ERROR';

export const SET_FILTRATION_PARAMS = 'SET_FILTRATION_PARAMS';
export const CLEAR_FILTRATION_PARAMS = 'CLEAR_FILTRATION_PARAMS';

export const SET_SEARCH_MODE = 'SET_SEARCH_MODE';
export const CLEAR_SEARCH_MODE = 'CLEAR_SEARCH_MODE';
export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const CLEAR_SEARCH_QUERY = 'CLEAR_SEARCH_QUERY';

export const SET_ONE_MOVIE_ID = 'SET_ONE_MOVIE_ID';

// Authentication
export const SET_USER_AUTHENTICATED = 'SET_USER_AUTHENTICATED';
export const SET_USER_UNAUTHENTICATED = 'SET_USER_UNAUTHENTICATED';
